config/routes.rb
Rails.application.routes.draw do
  resources :dive_service_member_gears
  resources :dive_service_members
  resources :certifications_members
  resources :members_clients
  resources :certifications
  resources :certification_types
  resources :dive_service_member_types
  resources :gears
  resources :gear_types
  resources :gear_sizes
  resources :dive_service_spots
  resources :dive_services
  resources :dive_spots
  resources :boat_documents
  resources :boats
  resources :boat_document_types

end

app/models/dive_spot.rb
class DiveSpot < ActiveRecord::Base
  has_many :dive_service_spots, foreign_key: 'dive_spot_id'
end

app/controllers/dive_spots_controller.rb
class DiveSpotsController < ApplicationController
  before_action :set_dive_spot, only: [:show, :edit, :update, :destroy]

  # GET /dive_spots
  # GET /dive_spots.json
  def index
    @dive_spots = DiveSpot.all
  end

  # GET /dive_spots/1
  # GET /dive_spots/1.json
  def show
  end

  # GET /dive_spots/new
  def new
    @dive_spot = DiveSpot.new
  end

  # GET /dive_spots/1/edit
  def edit
  end

  # POST /dive_spots
  # POST /dive_spots.json
  def create
    @dive_spot = DiveSpot.new(dive_spot_params)

    respond_to do |format|
      if @dive_spot.save
        format.html { redirect_to @dive_spot, notice: 'Dive spot was successfully created.' }
        format.json { render :show, status: :created, location: @dive_spot }
      else
        format.html { render :new }
        format.json { render json: @dive_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dive_spots/1
  # PATCH/PUT /dive_spots/1.json
  def update
    respond_to do |format|
      if @dive_spot.update(dive_spot_params)
        format.html { redirect_to @dive_spot, notice: 'Dive spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @dive_spot }
      else
        format.html { render :edit }
        format.json { render json: @dive_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dive_spots/1
  # DELETE /dive_spots/1.json
  def destroy
    @dive_spot.destroy
    respond_to do |format|
      format.html { redirect_to dive_spots_url, notice: 'Dive spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dive_spot
      @dive_spot = DiveSpot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dive_spot_params
      params.require(:dive_spot).permit(:name, :max_depth, :min_depth, :sea_life, :coordenads, :notes)
    end
end

app/helpers/dive_spots_helper.rb
module DiveSpotsHelper
end

app/views/dive_spots/_form.html.erb
<%= form_for(@dive_spot) do |f| %>
  <% if @dive_spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dive_spot.errors.count, "error") %> prohibited this dive_spot from being saved:</h2>

      <ul>
      <% @dive_spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :max_depth %><br>
    <%= f.number_field :max_depth %>
  </div>
  <div class="field">
    <%= f.label :min_depth %><br>
    <%= f.number_field :min_depth %>
  </div>
  <div class="field">
    <%= f.label :sea_life %><br>
    <%= f.text_field :sea_life %>
  </div>
  <div class="field">
    <%= f.label :coordenads %><br>
    <%= f.text_field :coordenads %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dive_spots/edit.html.erb
<h1>Editing Dive Spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @dive_spot %> |
<%= link_to 'Back', dive_spots_path %>

app/views/dive_spots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dive Spots</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Max depth</th>
      <th>Min depth</th>
      <th>Sea life</th>
      <th>Coordenads</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dive_spots.each do |dive_spot| %>
      <tr>
        <td><%= dive_spot.name %></td>
        <td><%= dive_spot.max_depth %></td>
        <td><%= dive_spot.min_depth %></td>
        <td><%= dive_spot.sea_life %></td>
        <td><%= dive_spot.coordenads %></td>
        <td><%= dive_spot.notes %></td>
        <td><%= link_to 'Show', dive_spot %></td>
        <td><%= link_to 'Edit', edit_dive_spot_path(dive_spot) %></td>
        <td><%= link_to 'Destroy', dive_spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dive spot', new_dive_spot_path %>

app/views/dive_spots/new.html.erb
<h1>New Dive Spot</h1>

<%= render 'form' %>

<%= link_to 'Back', dive_spots_path %>

app/views/dive_spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dive_spot.name %>
</p>

<p>
  <strong>Max depth:</strong>
  <%= @dive_spot.max_depth %>
</p>

<p>
  <strong>Min depth:</strong>
  <%= @dive_spot.min_depth %>
</p>

<p>
  <strong>Sea life:</strong>
  <%= @dive_spot.sea_life %>
</p>

<p>
  <strong>Coordenads:</strong>
  <%= @dive_spot.coordenads %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @dive_spot.notes %>
</p>

<%= link_to 'Edit', edit_dive_spot_path(@dive_spot) %> |
<%= link_to 'Back', dive_spots_path %>