config/routes.rb
Rails.application.routes.draw do
  resources :dive_service_member_gears
  resources :dive_service_members
  resources :certifications_members
  resources :members_clients
  resources :certifications
  resources :certification_types
  resources :dive_service_member_types
  resources :gears
  resources :gear_types
  resources :gear_sizes
  resources :dive_service_spots
  resources :dive_services
  resources :dive_spots
  resources :boat_documents
  resources :boats
  resources :boat_document_types

end

app/models/certification.rb
class Certification < ActiveRecord::Base
  belongs_to :certification_type, foreign_key: 'certification_type_id'
  has_many :certifications_members, foreign_key: 'certification_id'
end

app/models/certification_type.rb
class CertificationType < ActiveRecord::Base
  has_many :certifications, foreign_key: 'certification_type_id'
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  before_action :set_certification, only: [:show, :edit, :update, :destroy]

  # GET /certifications
  # GET /certifications.json
  def index
    @certifications = Certification.all
  end

  # GET /certifications/1
  # GET /certifications/1.json
  def show
  end

  # GET /certifications/new
  def new
    @certification = Certification.new
  end

  # GET /certifications/1/edit
  def edit
  end

  # POST /certifications
  # POST /certifications.json
  def create
    @certification = Certification.new(certification_params)

    respond_to do |format|
      if @certification.save
        format.html { redirect_to @certification, notice: 'Certification was successfully created.' }
        format.json { render :show, status: :created, location: @certification }
      else
        format.html { render :new }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certifications/1
  # PATCH/PUT /certifications/1.json
  def update
    respond_to do |format|
      if @certification.update(certification_params)
        format.html { redirect_to @certification, notice: 'Certification was successfully updated.' }
        format.json { render :show, status: :ok, location: @certification }
      else
        format.html { render :edit }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certifications/1
  # DELETE /certifications/1.json
  def destroy
    @certification.destroy
    respond_to do |format|
      format.html { redirect_to certifications_url, notice: 'Certification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certification
      @certification = Certification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certification_params
      params.require(:certification).permit(:name, :level, :notes)
    end
end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/views/certifications/_form.html.erb
<%= form_for(@certification) do |f| %>
  <% if @certification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certification.errors.count, "error") %> prohibited this certification from being saved:</h2>

      <ul>
      <% @certification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/certifications/edit.html.erb
<h1>Editing Certification</h1>

<%= render 'form' %>

<%= link_to 'Show', @certification %> |
<%= link_to 'Back', certifications_path %>

app/views/certifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Certifications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @certifications.each do |certification| %>
      <tr>
        <td><%= certification.name %></td>
        <td><%= certification.level %></td>
        <td><%= certification.notes %></td>
        <td><%= link_to 'Show', certification %></td>
        <td><%= link_to 'Edit', edit_certification_path(certification) %></td>
        <td><%= link_to 'Destroy', certification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Certification', new_certification_path %>

app/views/certifications/new.html.erb
<h1>New Certification</h1>

<%= render 'form' %>

<%= link_to 'Back', certifications_path %>

app/views/certifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @certification.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @certification.level %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @certification.notes %>
</p>

<%= link_to 'Edit', edit_certification_path(@certification) %> |
<%= link_to 'Back', certifications_path %>