config/routes.rb
Rails.application.routes.draw do
  resources :dive_service_member_gears
  resources :dive_service_members
  resources :certifications_members
  resources :members_clients
  resources :certifications
  resources :certification_types
  resources :dive_service_member_types
  resources :gears
  resources :gear_types
  resources :gear_sizes
  resources :dive_service_spots
  resources :dive_services
  resources :dive_spots
  resources :boat_documents
  resources :boats
  resources :boat_document_types

end

app/models/dive_service_spot.rb
class DiveServiceSpot < ActiveRecord::Base
  has_many :dive_service_members, foreign_key: 'dive_service_spot_id'
  belongs_to :dive_spot, foreign_key: 'dive_spot_id'
  belongs_to :dive_service, foreign_key: 'dive_service_id'
end

app/controllers/dive_service_spots_controller.rb
class DiveServiceSpotsController < ApplicationController
  before_action :set_dive_service_spot, only: [:show, :edit, :update, :destroy]

  # GET /dive_service_spots
  # GET /dive_service_spots.json
  def index
    @dive_service_spots = DiveServiceSpot.all
  end

  # GET /dive_service_spots/1
  # GET /dive_service_spots/1.json
  def show
  end

  # GET /dive_service_spots/new
  def new
    @dive_service_spot = DiveServiceSpot.new
  end

  # GET /dive_service_spots/1/edit
  def edit
  end

  # POST /dive_service_spots
  # POST /dive_service_spots.json
  def create
    @dive_service_spot = DiveServiceSpot.new(dive_service_spot_params)

    respond_to do |format|
      if @dive_service_spot.save
        format.html { redirect_to @dive_service_spot, notice: 'Dive service spot was successfully created.' }
        format.json { render :show, status: :created, location: @dive_service_spot }
      else
        format.html { render :new }
        format.json { render json: @dive_service_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dive_service_spots/1
  # PATCH/PUT /dive_service_spots/1.json
  def update
    respond_to do |format|
      if @dive_service_spot.update(dive_service_spot_params)
        format.html { redirect_to @dive_service_spot, notice: 'Dive service spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @dive_service_spot }
      else
        format.html { render :edit }
        format.json { render json: @dive_service_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dive_service_spots/1
  # DELETE /dive_service_spots/1.json
  def destroy
    @dive_service_spot.destroy
    respond_to do |format|
      format.html { redirect_to dive_service_spots_url, notice: 'Dive service spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dive_service_spot
      @dive_service_spot = DiveServiceSpot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dive_service_spot_params
      params.fetch(:dive_service_spot, {})
    end
end

app/helpers/dive_service_spots_helper.rb
module DiveServiceSpotsHelper
end

app/views/dive_service_spots/_form.html.erb
<%= form_for(@dive_service_spot) do |f| %>
  <% if @dive_service_spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dive_service_spot.errors.count, "error") %> prohibited this dive_service_spot from being saved:</h2>

      <ul>
      <% @dive_service_spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dive_service_spots/edit.html.erb
<h1>Editing Dive Service Spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @dive_service_spot %> |
<%= link_to 'Back', dive_service_spots_path %>

app/views/dive_service_spots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dive Service Spots</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dive_service_spots.each do |dive_service_spot| %>
      <tr>
        <td><%= link_to 'Show', dive_service_spot %></td>
        <td><%= link_to 'Edit', edit_dive_service_spot_path(dive_service_spot) %></td>
        <td><%= link_to 'Destroy', dive_service_spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dive service spot', new_dive_service_spot_path %>

app/views/dive_service_spots/new.html.erb
<h1>New Dive Service Spot</h1>

<%= render 'form' %>

<%= link_to 'Back', dive_service_spots_path %>

app/views/dive_service_spots/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dive_service_spot_path(@dive_service_spot) %> |
<%= link_to 'Back', dive_service_spots_path %>