config/routes.rb
Rails.application.routes.draw do
  resources :dive_service_member_gears
  resources :dive_service_members
  resources :certifications_members
  resources :members_clients
  resources :certifications
  resources :certification_types
  resources :dive_service_member_types
  resources :gears
  resources :gear_types
  resources :gear_sizes
  resources :dive_service_spots
  resources :dive_services
  resources :dive_spots
  resources :boat_documents
  resources :boats
  resources :boat_document_types

end

app/models/boat.rb
class Boat < ActiveRecord::Base
  has_many :boat_documents, foreign_key: 'boat_id'
  has_many :dive_services, foreign_key: 'boat_id'
end

app/models/boat_document.rb
class BoatDocument < ActiveRecord::Base
  belongs_to :boat, foreign_key: 'boat_id'
  belongs_to :boat_document_type, foreign_key: 'boat_document_type_id'
end

app/models/boat_document_type.rb
class BoatDocumentType < ActiveRecord::Base
  has_many :boat_documents, foreign_key: 'boat_document_type_id'
end

app/models/certification.rb
class Certification < ActiveRecord::Base
  belongs_to :certification_type, foreign_key: 'certification_type_id'
  has_many :certifications_members, foreign_key: 'certification_id'
end

app/models/certification_type.rb
class CertificationType < ActiveRecord::Base
  has_many :certifications, foreign_key: 'certification_type_id'
end

app/models/certifications_member.rb
class CertificationsMember < ActiveRecord::Base
  belongs_to :certification, foreign_key: 'certification_id'
  belongs_to :members_client, foreign_key: 'members_client_id'
end

app/models/dive_service.rb
class DiveService < ActiveRecord::Base
  belongs_to :boat, foreign_key: 'boat_id'
  has_many :dive_service_spots, foreign_key: 'dive_service_id'
end

app/models/dive_service_member.rb
class DiveServiceMember < ActiveRecord::Base
  belongs_to :members_client, foreign_key: 'members_client_id'
  belongs_to :dive_service_member_type, foreign_key: 'dive_service_member_type_id'
  belongs_to :dive_service_spot, foreign_key: 'dive_service_spot_id'
  has_many :dive_service_member_gears, foreign_key: 'dive_service_member_id'
end

app/models/dive_service_spot.rb
class DiveServiceSpot < ActiveRecord::Base
  has_many :dive_service_members, foreign_key: 'dive_service_spot_id'
  belongs_to :dive_spot, foreign_key: 'dive_spot_id'
  belongs_to :dive_service, foreign_key: 'dive_service_id'
end

app/models/dive_spot.rb
class DiveSpot < ActiveRecord::Base
  has_many :dive_service_spots, foreign_key: 'dive_spot_id'
end

app/models/gear.rb
class Gear < ActiveRecord::Base
  belongs_to :gear_size, foreign_key: 'gear_size_id'
  belongs_to :gear_type, foreign_key: 'gear_type_id'
  has_many :dive_service_member_gears, foreign_key: 'gear_id'
end

app/models/gear_size.rb
class GearSize < ActiveRecord::Base
  has_many :gears, foreign_key: 'gear_size_id'
end

app/models/gear_type.rb
class GearType < ActiveRecord::Base
  has_many :gears, foreign_key: 'gear_type_id'
end

app/models/members_client.rb
class MembersClient < ActiveRecord::Base
  has_many :certifications_members, foreign_key: 'members_client_id'
  has_many :dive_service_members, foreign_key: 'members_client_id'
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.all
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
  end

  # GET /boats/new
  def new
    @boat = Boat.new
  end

  # GET /boats/1/edit
  def edit
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:name, :mmsi, :horse_power, :seats)
    end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action :set_gear, only: [:show, :edit, :update, :destroy]

  # GET /gears
  # GET /gears.json
  def index
    @gears = Gear.all
  end

  # GET /gears/1
  # GET /gears/1.json
  def show
  end

  # GET /gears/new
  def new
    @gear = Gear.new
  end

  # GET /gears/1/edit
  def edit
  end

  # POST /gears
  # POST /gears.json
  def create
    @gear = Gear.new(gear_params)

    respond_to do |format|
      if @gear.save
        format.html { redirect_to @gear, notice: 'Gear was successfully created.' }
        format.json { render :show, status: :created, location: @gear }
      else
        format.html { render :new }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gears/1
  # PATCH/PUT /gears/1.json
  def update
    respond_to do |format|
      if @gear.update(gear_params)
        format.html { redirect_to @gear, notice: 'Gear was successfully updated.' }
        format.json { render :show, status: :ok, location: @gear }
      else
        format.html { render :edit }
        format.json { render json: @gear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gears/1
  # DELETE /gears/1.json
  def destroy
    @gear.destroy
    respond_to do |format|
      format.html { redirect_to gears_url, notice: 'Gear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gear
      @gear = Gear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gear_params
      params.require(:gear).permit(:reference, :purchase_date, :sell_date, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/dive_services_helper.rb
module DiveServicesHelper
end

app/helpers/dive_spots_helper.rb
module DiveSpotsHelper
end

app/helpers/gear_sizes_helper.rb
module GearSizesHelper
end

app/helpers/gear_types_helper.rb
module GearTypesHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/views/boats/_form.html.erb
<%= form_for(@boat) do |f| %>
  <% if @boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% @boat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mmsi %><br>
    <%= f.text_field :mmsi %>
  </div>
  <div class="field">
    <%= f.label :horse_power %><br>
    <%= f.text_field :horse_power %>
  </div>
  <div class="field">
    <%= f.label :seats %><br>
    <%= f.number_field :seats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boats/edit.html.erb
<h1>Editing Boat</h1>

<%= render 'form' %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mmsi</th>
      <th>Horse power</th>
      <th>Seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boats.each do |boat| %>
      <tr>
        <td><%= boat.name %></td>
        <td><%= boat.mmsi %></td>
        <td><%= boat.horse_power %></td>
        <td><%= boat.seats %></td>
        <td><%= link_to 'Show', boat %></td>
        <td><%= link_to 'Edit', edit_boat_path(boat) %></td>
        <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boat', new_boat_path %>

app/views/boats/new.html.erb
<h1>New Boat</h1>

<%= render 'form' %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @boat.name %>
</p>

<p>
  <strong>Mmsi:</strong>
  <%= @boat.mmsi %>
</p>

<p>
  <strong>Horse power:</strong>
  <%= @boat.horse_power %>
</p>

<p>
  <strong>Seats:</strong>
  <%= @boat.seats %>
</p>

<%= link_to 'Edit', edit_boat_path(@boat) %> |
<%= link_to 'Back', boats_path %>